name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🦄 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bugfixes'
    labels:
      - 'bugfix'
  - title: '📖 Documentation'
    labels:
      - 'documentation'
  - title: '📦 Dependencies'
    labels:
      - 'javascript'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
